name: pyReconstruct Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout pyReconstruct code
      uses: actions/checkout@v2
      with:
        repository: SynapseWeb/pyReconstruct
        ref: main

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: tiffhuff/pyreconstruct:latest

